package com.zhqz.wisc.data.DbDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhqz.wisc.data.model.CardInfoData;
import com.zhqz.wisc.data.model.FingerTeacherUsers;
import com.zhqz.wisc.data.model.CourseTwo;
import com.zhqz.wisc.data.model.AttendanceData;
import com.zhqz.wisc.data.model.Course;
import com.zhqz.wisc.data.model.Teacher;
import com.zhqz.wisc.data.model.Student;
import com.zhqz.wisc.data.model.NoWifiData;
import com.zhqz.wisc.data.model.ZuoPinDb;
import com.zhqz.wisc.data.model.FingerUsers;
import com.zhqz.wisc.libraryui.main.LibraryReshuModel;

import com.zhqz.wisc.data.DbDao.CardInfoDataDao;
import com.zhqz.wisc.data.DbDao.FingerTeacherUsersDao;
import com.zhqz.wisc.data.DbDao.CourseTwoDao;
import com.zhqz.wisc.data.DbDao.AttendanceDataDao;
import com.zhqz.wisc.data.DbDao.CourseDao;
import com.zhqz.wisc.data.DbDao.TeacherDao;
import com.zhqz.wisc.data.DbDao.StudentDao;
import com.zhqz.wisc.data.DbDao.NoWifiDataDao;
import com.zhqz.wisc.data.DbDao.ZuoPinDbDao;
import com.zhqz.wisc.data.DbDao.FingerUsersDao;
import com.zhqz.wisc.data.DbDao.LibraryReshuModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardInfoDataDaoConfig;
    private final DaoConfig fingerTeacherUsersDaoConfig;
    private final DaoConfig courseTwoDaoConfig;
    private final DaoConfig attendanceDataDaoConfig;
    private final DaoConfig courseDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig noWifiDataDaoConfig;
    private final DaoConfig zuoPinDbDaoConfig;
    private final DaoConfig fingerUsersDaoConfig;
    private final DaoConfig libraryReshuModelDaoConfig;

    private final CardInfoDataDao cardInfoDataDao;
    private final FingerTeacherUsersDao fingerTeacherUsersDao;
    private final CourseTwoDao courseTwoDao;
    private final AttendanceDataDao attendanceDataDao;
    private final CourseDao courseDao;
    private final TeacherDao teacherDao;
    private final StudentDao studentDao;
    private final NoWifiDataDao noWifiDataDao;
    private final ZuoPinDbDao zuoPinDbDao;
    private final FingerUsersDao fingerUsersDao;
    private final LibraryReshuModelDao libraryReshuModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardInfoDataDaoConfig = daoConfigMap.get(CardInfoDataDao.class).clone();
        cardInfoDataDaoConfig.initIdentityScope(type);

        fingerTeacherUsersDaoConfig = daoConfigMap.get(FingerTeacherUsersDao.class).clone();
        fingerTeacherUsersDaoConfig.initIdentityScope(type);

        courseTwoDaoConfig = daoConfigMap.get(CourseTwoDao.class).clone();
        courseTwoDaoConfig.initIdentityScope(type);

        attendanceDataDaoConfig = daoConfigMap.get(AttendanceDataDao.class).clone();
        attendanceDataDaoConfig.initIdentityScope(type);

        courseDaoConfig = daoConfigMap.get(CourseDao.class).clone();
        courseDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        noWifiDataDaoConfig = daoConfigMap.get(NoWifiDataDao.class).clone();
        noWifiDataDaoConfig.initIdentityScope(type);

        zuoPinDbDaoConfig = daoConfigMap.get(ZuoPinDbDao.class).clone();
        zuoPinDbDaoConfig.initIdentityScope(type);

        fingerUsersDaoConfig = daoConfigMap.get(FingerUsersDao.class).clone();
        fingerUsersDaoConfig.initIdentityScope(type);

        libraryReshuModelDaoConfig = daoConfigMap.get(LibraryReshuModelDao.class).clone();
        libraryReshuModelDaoConfig.initIdentityScope(type);

        cardInfoDataDao = new CardInfoDataDao(cardInfoDataDaoConfig, this);
        fingerTeacherUsersDao = new FingerTeacherUsersDao(fingerTeacherUsersDaoConfig, this);
        courseTwoDao = new CourseTwoDao(courseTwoDaoConfig, this);
        attendanceDataDao = new AttendanceDataDao(attendanceDataDaoConfig, this);
        courseDao = new CourseDao(courseDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        noWifiDataDao = new NoWifiDataDao(noWifiDataDaoConfig, this);
        zuoPinDbDao = new ZuoPinDbDao(zuoPinDbDaoConfig, this);
        fingerUsersDao = new FingerUsersDao(fingerUsersDaoConfig, this);
        libraryReshuModelDao = new LibraryReshuModelDao(libraryReshuModelDaoConfig, this);

        registerDao(CardInfoData.class, cardInfoDataDao);
        registerDao(FingerTeacherUsers.class, fingerTeacherUsersDao);
        registerDao(CourseTwo.class, courseTwoDao);
        registerDao(AttendanceData.class, attendanceDataDao);
        registerDao(Course.class, courseDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(Student.class, studentDao);
        registerDao(NoWifiData.class, noWifiDataDao);
        registerDao(ZuoPinDb.class, zuoPinDbDao);
        registerDao(FingerUsers.class, fingerUsersDao);
        registerDao(LibraryReshuModel.class, libraryReshuModelDao);
    }
    
    public void clear() {
        cardInfoDataDaoConfig.clearIdentityScope();
        fingerTeacherUsersDaoConfig.clearIdentityScope();
        courseTwoDaoConfig.clearIdentityScope();
        attendanceDataDaoConfig.clearIdentityScope();
        courseDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        noWifiDataDaoConfig.clearIdentityScope();
        zuoPinDbDaoConfig.clearIdentityScope();
        fingerUsersDaoConfig.clearIdentityScope();
        libraryReshuModelDaoConfig.clearIdentityScope();
    }

    public CardInfoDataDao getCardInfoDataDao() {
        return cardInfoDataDao;
    }

    public FingerTeacherUsersDao getFingerTeacherUsersDao() {
        return fingerTeacherUsersDao;
    }

    public CourseTwoDao getCourseTwoDao() {
        return courseTwoDao;
    }

    public AttendanceDataDao getAttendanceDataDao() {
        return attendanceDataDao;
    }

    public CourseDao getCourseDao() {
        return courseDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public NoWifiDataDao getNoWifiDataDao() {
        return noWifiDataDao;
    }

    public ZuoPinDbDao getZuoPinDbDao() {
        return zuoPinDbDao;
    }

    public FingerUsersDao getFingerUsersDao() {
        return fingerUsersDao;
    }

    public LibraryReshuModelDao getLibraryReshuModelDao() {
        return libraryReshuModelDao;
    }

}
