package com.zhqz.wisc.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhqz.wisc.data.model.Student;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STUDENT".
*/
public class StudentDao extends AbstractDao<Student, Long> {

    public static final String TABLENAME = "STUDENT";

    /**
     * Properties of entity Student.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property StudentId = new Property(0, int.class, "studentId", false, "STUDENT_ID");
        public final static Property StudentName = new Property(1, String.class, "studentName", false, "STUDENT_NAME");
        public final static Property CardNumber = new Property(2, String.class, "cardNumber", false, "CARD_NUMBER");
        public final static Property StudentNumber = new Property(3, String.class, "studentNumber", false, "STUDENT_NUMBER");
        public final static Property Attendancedate = new Property(4, String.class, "attendancedate", false, "ATTENDANCEDATE");
        public final static Property AttendanceId = new Property(5, long.class, "attendanceId", true, "_id");
        public final static Property Status = new Property(6, int.class, "status", false, "STATUS");
        public final static Property Picture = new Property(7, String.class, "picture", false, "PICTURE");
    }


    public StudentDao(DaoConfig config) {
        super(config);
    }
    
    public StudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STUDENT\" (" + //
                "\"STUDENT_ID\" INTEGER NOT NULL ," + // 0: studentId
                "\"STUDENT_NAME\" TEXT," + // 1: studentName
                "\"CARD_NUMBER\" TEXT," + // 2: cardNumber
                "\"STUDENT_NUMBER\" TEXT," + // 3: studentNumber
                "\"ATTENDANCEDATE\" TEXT," + // 4: attendancedate
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 5: attendanceId
                "\"STATUS\" INTEGER NOT NULL ," + // 6: status
                "\"PICTURE\" TEXT);"); // 7: picture
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Student entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStudentId());
 
        String studentName = entity.getStudentName();
        if (studentName != null) {
            stmt.bindString(2, studentName);
        }
 
        String cardNumber = entity.getCardNumber();
        if (cardNumber != null) {
            stmt.bindString(3, cardNumber);
        }
 
        String studentNumber = entity.getStudentNumber();
        if (studentNumber != null) {
            stmt.bindString(4, studentNumber);
        }
 
        String attendancedate = entity.getAttendancedate();
        if (attendancedate != null) {
            stmt.bindString(5, attendancedate);
        }
        stmt.bindLong(6, entity.getAttendanceId());
        stmt.bindLong(7, entity.getStatus());
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(8, picture);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Student entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStudentId());
 
        String studentName = entity.getStudentName();
        if (studentName != null) {
            stmt.bindString(2, studentName);
        }
 
        String cardNumber = entity.getCardNumber();
        if (cardNumber != null) {
            stmt.bindString(3, cardNumber);
        }
 
        String studentNumber = entity.getStudentNumber();
        if (studentNumber != null) {
            stmt.bindString(4, studentNumber);
        }
 
        String attendancedate = entity.getAttendancedate();
        if (attendancedate != null) {
            stmt.bindString(5, attendancedate);
        }
        stmt.bindLong(6, entity.getAttendanceId());
        stmt.bindLong(7, entity.getStatus());
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(8, picture);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 5);
    }    

    @Override
    public Student readEntity(Cursor cursor, int offset) {
        Student entity = new Student( //
            cursor.getInt(offset + 0), // studentId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // studentName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // cardNumber
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // studentNumber
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // attendancedate
            cursor.getLong(offset + 5), // attendanceId
            cursor.getInt(offset + 6), // status
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // picture
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Student entity, int offset) {
        entity.setStudentId(cursor.getInt(offset + 0));
        entity.setStudentName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCardNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStudentNumber(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAttendancedate(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAttendanceId(cursor.getLong(offset + 5));
        entity.setStatus(cursor.getInt(offset + 6));
        entity.setPicture(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Student entity, long rowId) {
        entity.setAttendanceId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Student entity) {
        if(entity != null) {
            return entity.getAttendanceId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Student entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
